ibs_local_system_bk/config/routes.rb
Rails.application.routes.draw do

  namespace :ect do

    resources :engagements do

      resource :class_plan_values do
        get :erp_calculate
        get :export
      end

      resource :local_job_levels do
        get :select
        get :set
      end

      resources :plan_versions do
        get :class_plan_values
      end
    end

    resource :ajax_get_data do
      get :get_profile_center
    end
  end

end

ibs_local_system_bk/app/models/ect/activity_types.rb
class ActivityTypes < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/alert_rules.rb
class AlertRules < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/class_actual_values.rb
class ClassActualValues < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/companies.rb
class Companies < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/engagement.rb
class Engagement < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/local_job_levels.rb
class LocalJobLevels < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/plan_values.rb
class PlanValues < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/plan_versions.rb
class PlanVersions < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/profit_centers.rb
class ProfitCenters < ActiveRecord::Base
end

ibs_local_system_bk/app/models/ect/team_members.rb
class TeamMembers < ActiveRecord::Base
end

ibs_local_system_bk/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ibs_local_system_bk/app/controllers/ect/ajax_get_data_controller.rb
class Ect::AjaxGetDataController < ApplicationController

  #assets/javascripts/application.jsから呼ばれる
  #Engagement一覧画面（検索用）
  def get_profile_center

    #選んだコード
    company_code = params['company_code'].to_i

    #仮のパラメータ
    json = {}
    for i in 0..5 do
      json[i] = {}
      json[i]['value'] = i      #ID取得
      json[i]['name']  = "ProfileCenter=#{i.to_s}_CompanyCode=#{company_code.to_s}"   #表示する名前を入れておく
    end

    #to_jsonで変換する
    render :text => json.to_json, :type=> "text/plain"
    return
  end

end

ibs_local_system_bk/app/controllers/ect/class_plan_values_controller.rb
class Ect::ClassPlanValuesController < ApplicationController

  def show
    #index

    #
    @engagement_id = params[:engagement_id].to_s

    #更新出来る
    @bk_flag = false

  end

  def edit
    #edit画面

    @engagement_id = params[:engagement_id].to_s

  end

  def update
    #update処理
  end


end

ibs_local_system_bk/app/controllers/ect/engagements_controller.rb
class Ect::EngagementsController < ApplicationController
  before_action :set_engagement, only: [:show, :edit, :update, :destroy]

  # GET /engagements
  # GET /engagements.json
  def index
    #@engagements = Engagement.all
    @engagements = Engagement.page(params[:page]).per(3).order('id DESC')

    @total_count = @engagements.count

    #メモ(作業予定)
    #
    #(EngagementsController)
    #
    #  ・Searchをおした時
    #    => 下にリスト表示
    #
    #  (Search後)
    #  ・Exportをおした時
    #  Excelにリストを出力
    #
    #  ・EngagementNameのリンクをクリックした時に
    #  ClassPlanValuesControllerへ遷移する
    #
    # => (ClassPlanValuesController)
    #     ・Editを押した時は
    #     ClassPlanValues/Editに遷移
    #
    #      => ・Class Settingを押した時は
    #         LocalJobLevelsControllerに遷移
    #
    #     ・Version Listを押した時は
    #     PlanVersionsControllerへ遷移する
    #
    #     ・Engagement Detailをおした時は
    #     ひとつ戻ってEngagementsController/Showへ遷移する
    #

  end

  # GET /engagements/1
  # GET /engagements/1.json
  def show
  end

  # GET /engagements/new
  def new
    @engagement = Engagement.new
  end

  # GET /engagements/1/edit
  def edit
  end

  # POST /engagements
  # POST /engagements.json
  def create
    @engagement = Engagement.new(engagement_params)

    respond_to do |format|
      if @engagement.save
        #format.html { redirect_to @engagement, notice: 'Engagement was successfully created.' }
        #format.json { render :show, status: :created, location: @engagement }
        format.html { redirect_to engagement_engagements_url, notice: 'Engagement was successfully created.' }
        format.json { render :index, status: :created, location: @engagement }
      else
        format.html { render :new }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engagements/1
  # PATCH/PUT /engagements/1.json
  def update
    respond_to do |format|
      if @engagement.update(engagement_params)
        #format.html { redirect_to @engagement, notice: 'Engagement was successfully updated.' }
        #format.json { render :show, status: :ok, location: @engagement }
        format.html { redirect_to engagement_engagements_url, notice: 'Engagement was successfully updated.' }
        format.json { render :index, status: :ok, location: @engagement }
      else
        format.html { render :edit }
        format.json { render json: @engagement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engagements/1
  # DELETE /engagements/1.json
  def destroy
    @engagement.destroy
    respond_to do |format|
      format.html { redirect_to engagement_engagements_url, notice: 'Engagement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engagement
      # @engagement = Engagement.find(params[:id])
      @engagement = Engagement.where(:engagement_number => params[:id]).order(:id => :desc)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engagement_params
      params.require(:engagement).permit(:engagement_number, :engagement_descr, :engagement_legacy_number, :em_sap_personnel_number, :em_legacy_emplid, :ep_sap_personnel_number, :ep_legacy_emplid, :erp_realization_rate, :entity_number, :profit_center, :local_service_type, :local_service_type_descr, :company_code, :engagement_status, :engagement_type, :profit_center_descr, :assistant_name, :assistant_sap_personnel_number, :assistant_legacy_emplid, :em_name, :ep_name, :engagement_type_descr, :entity_name, :lead_engagement_number, :san_expirty_date, :confidential_engagment, :san_start_date, :contract_amount, :fiscal_end_date, :contract_type, :deleted_at, :created_at, :updated_at)
    end
end

ibs_local_system_bk/app/controllers/ect/local_job_levels_controller.rb
class Ect::LocalJobLevelsController < ApplicationController

  #選択
  def select
    @engagement_id = params[:engagement_id].to_s
  end

  #更新
  def set
    @engagement_id = params[:engagement_id].to_s
  end

end

ibs_local_system_bk/app/controllers/ect/plan_versions_controller.rb
class Ect::PlanVersionsController < ApplicationController

  def index
    #index
    @engagement_id = params[:engagement_id].to_s
  end

  def class_plan_values
    #class_plan_values
    @engagement_id = params[:engagement_id].to_s
    @plan_version_id = params[:plan_version_id].to_s

    #更新できない
    @bk_flag = true

    #前のshowを使う
    render :template => "ect/class_plan_values/show"

  end

end

ibs_local_system_bk/app/helpers/application_helper.rb
module ApplicationHelper
end

ibs_local_system_bk/app/helpers/ect/class_plan_values_helper.rb
module Ect::ClassPlanValuesHelper
end

ibs_local_system_bk/app/helpers/ect/engagements_helper.rb
module Ect::EngagementsHelper
end

ibs_local_system_bk/app/helpers/ect/local_job_levels_helper.rb
module Ect::LocalJobLevelsHelper
end

ibs_local_system_bk/app/helpers/ect/plan_versions_helper.rb
module Ect::PlanVersionsHelper
end

ibs_local_system_bk/app/views/ect/class_plan_values/edit.html.erb
<h2>計画工数編集画面</h2>

<div class="panel-group" id="accordion">
<div class="panel-heading">
<h4 class="panel-title">
	<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
		Fillter
	</a>
</h4>
</div>
<div id="collapseOne" class="panel-collapse collapse in">
<div class="panel-body">

	<!-- ここから閉じる -->
	<table class="table table-bordered">
		<form action="" method="post" name="form1" id="">
		<thead>
		</thead>
		<tbody class="col-xs-12">

		<tr>
			<td class="info text-right">Engagement</td>
			<td>コード＆名前</td>
			<td class="info text-right">Start Date/End Date</td>
			<td>2015/06/01 ～ 2015/09/01</td>
			<td class="info text-right">Version</td>
			<td>1</td>
		</tr>


		<tr>
			<td class="info text-right">Contract Amount</td>
			<td>￥900,000,000</td>
			<td class="info text-right">Actual Subcontract Fee</td>
			<td>￥900,000,000</td>
			<td class="info text-right">ERP(IBS)</td>
			<td>50.00%</td>
		</tr>

		<tr>
			<td class="info text-right">Total Contract Amount</td>
			<td>￥900,000,000</td>
			<td class="info text-right">Planned Subcontract Fee</td>
			<td>￥900,000,000</td>
			<td class="info text-right">Planned ERP</td>
			<td>50.00%</td>
		</tr>

		</form>
		</tbody>
	</table>


	<!-- button -->
	<table class="col-xs-6">
		<tr>
			<td><%= button_to('Back To Show', ect_engagement_class_plan_values_path(@engagement_id), :method => :get, :class => "btn btn-primary")  %></td>
			<td><button type="submit" class="btn btn-primary">ERP Calculatet</button></td>
			<td><button type="submit" class="btn btn-primary">Save</button></td>
			<td><%= button_to('Class Setting', select_ect_engagement_local_job_levels_path(@engagement_id), :method => :get, :class => "btn btn-primary")  %></td>
		</tr>
	</table>

	<!-- ここまで閉じる -->
  </div>
</div>
</div>
</div>


<br>


<table>

	<tr>
		<th>Class</th>
		<th>Plan</th>
	</tr>

</table>

ibs_local_system_bk/app/views/ect/class_plan_values/show.html.erb
<h2>計画工数照会画面</h2>

<div class="panel-group" id="accordion">
<div class="panel-heading">
<h4 class="panel-title">
	<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
		Fillter
	</a>
</h4>
</div>
<div id="collapseOne" class="panel-collapse collapse in">
<div class="panel-body">

	<!-- ここから閉じる -->
	<table class="table table-bordered">
		<form action="" method="post" name="form1" id="">
		<thead>
		</thead>
		<tbody class="col-xs-12">

		<tr>
			<td class="info text-right">Engagement</td>
			<td>コード＆名前</td>
			<td class="info text-right">Start Date/End Date</td>
			<td>2015/06/01 ～ 2015/09/01</td>
			<td class="info text-right">Version</td>
			<td>1</td>
		</tr>


		<tr>
			<td class="info text-right">Contract Amount</td>
			<td>￥900,000,000</td>
			<td class="info text-right">Actual Subcontract Fee</td>
			<td>￥900,000,000</td>
			<td class="info text-right">ERP(IBS)</td>
			<td>50.00%</td>
		</tr>

		<tr>
			<td class="info text-right">Total Contract Amount</td>
			<td>￥900,000,000</td>
			<td class="info text-right">Planned Subcontract Fee</td>
			<td>￥900,000,000</td>
			<td class="info text-right">Planned ERP</td>
			<td>50.00%</td>
		</tr>

		</form>
		</tbody>
	</table>


	<!-- button -->
	<table class="col-xs-6">
		<tr>
			<td>
				<% if @bk_flag == true %>
					<button disabled class="btn btn-primary">Edit</button>
				<% else %>
					<%= button_to('Edit', edit_ect_engagement_class_plan_values_path(@engagement_id), :method => :get, :class => "btn btn-primary")  %>
				<% end %>
			</td>

			<td>
				<%= button_to('Version List', ect_engagement_plan_versions_path(@engagement_id), :method => :get, :class => "btn btn-primary")  %>
			</td>

			<td>
				<form action="<%= ect_engagement_path(:id => @engagement_id) %>" class="button_to" method="get" target="_blank">
					<input class="btn btn-primary" type="submit" value="Engagement Detail" />
				</form>
			</td>

			<td>
				<button type="submit" class="btn btn-primary">Export</button>
			</td>

			<td>
				<%= button_to('Back To List', ect_engagements_path, :method => :get, :class => "btn btn-primary")  %>
			</td>
		</tr>
	</table>

	<!-- ここまで閉じる -->
  </div>
</div>
</div>
</div>


<br>


<table>

	<tr>
		<th>Class</th>
		<th>Plan</th>
	</tr>

</table>

ibs_local_system_bk/app/views/ect/engagements/_form.html.erb
<%= form_for(@engagement, :url => ect_engagements_path(@engagement)) do |f| %>
  <% if @engagement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@engagement.errors.count, "error") %> prohibited this engagement from being saved:</h2>

      <ul>
      <% @engagement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :engagement_number %><br>
    <%= f.text_field :engagement_number %>
  </div>
  <div class="field">
    <%= f.label :engagement_descr %><br>
    <%= f.text_field :engagement_descr %>
  </div>
  <div class="field">
    <%= f.label :engagement_legacy_number %><br>
    <%= f.text_field :engagement_legacy_number %>
  </div>
  <div class="field">
    <%= f.label :em_sap_personnel_number %><br>
    <%= f.number_field :em_sap_personnel_number %>
  </div>
  <div class="field">
    <%= f.label :em_legacy_emplid %><br>
    <%= f.text_field :em_legacy_emplid %>
  </div>
  <div class="field">
    <%= f.label :ep_sap_personnel_number %><br>
    <%= f.number_field :ep_sap_personnel_number %>
  </div>
  <div class="field">
    <%= f.label :ep_legacy_emplid %><br>
    <%= f.text_field :ep_legacy_emplid %>
  </div>
  <div class="field">
    <%= f.label :erp_realization_rate %><br>
    <%= f.text_field :erp_realization_rate %>
  </div>
  <div class="field">
    <%= f.label :entity_number %><br>
    <%= f.text_field :entity_number %>
  </div>
  <div class="field">
    <%= f.label :profit_center %><br>
    <%= f.text_field :profit_center %>
  </div>
  <div class="field">
    <%= f.label :local_service_type %><br>
    <%= f.text_field :local_service_type %>
  </div>
  <div class="field">
    <%= f.label :local_service_type_descr %><br>
    <%= f.text_field :local_service_type_descr %>
  </div>
  <div class="field">
    <%= f.label :company_code %><br>
    <%= f.text_field :company_code %>
  </div>
  <div class="field">
    <%= f.label :engagement_status %><br>
    <%= f.text_field :engagement_status %>
  </div>
  <div class="field">
    <%= f.label :engagement_type %><br>
    <%= f.text_field :engagement_type %>
  </div>
  <div class="field">
    <%= f.label :profit_center_descr %><br>
    <%= f.text_field :profit_center_descr %>
  </div>
  <div class="field">
    <%= f.label :assistant_name %><br>
    <%= f.text_field :assistant_name %>
  </div>
  <div class="field">
    <%= f.label :assistant_sap_personnel_number %><br>
    <%= f.number_field :assistant_sap_personnel_number %>
  </div>
  <div class="field">
    <%= f.label :assistant_legacy_emplid %><br>
    <%= f.text_field :assistant_legacy_emplid %>
  </div>
  <div class="field">
    <%= f.label :em_name %><br>
    <%= f.text_field :em_name %>
  </div>
  <div class="field">
    <%= f.label :ep_name %><br>
    <%= f.text_field :ep_name %>
  </div>
  <div class="field">
    <%= f.label :engagement_type_descr %><br>
    <%= f.text_field :engagement_type_descr %>
  </div>
  <div class="field">
    <%= f.label :entity_name %><br>
    <%= f.text_field :entity_name %>
  </div>
  <div class="field">
    <%= f.label :lead_engagement_number %><br>
    <%= f.text_field :lead_engagement_number %>
  </div>
  <div class="field">
    <%= f.label :san_expirty_date %><br>
    <%= f.date_select :san_expirty_date %>
  </div>
  <div class="field">
    <%= f.label :confidential_engagment %><br>
    <%= f.text_field :confidential_engagment %>
  </div>
  <div class="field">
    <%= f.label :san_start_date %><br>
    <%= f.date_select :san_start_date %>
  </div>
  <div class="field">
    <%= f.label :contract_amount %><br>
    <%= f.text_field :contract_amount %>
  </div>
  <div class="field">
    <%= f.label :fiscal_end_date %><br>
    <%= f.date_select :fiscal_end_date %>
  </div>
  <div class="field">
    <%= f.label :contract_type %><br>
    <%= f.text_area :contract_type %>
  </div>
  <div class="field">
    <%= f.label :deleted_at %><br>
    <%= f.datetime_select :deleted_at %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ibs_local_system_bk/app/views/ect/engagements/edit.html.erb
<h1>Editing engagement</h1>

<%= render 'form' %>

<%= link_to 'Show', @engagement %> |
<%= link_to 'Back', ect_engagements_path %>

ibs_local_system_bk/app/views/ect/engagements/index.html.erb
	<h2>My Engagement一覧画面(Practice/Advane用)</h2>

	<div class="panel-group" id="accordion">
	<div class="panel-heading">
	<h4 class="panel-title">
		<a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
			Fillter
		</a>
	</h4>
	</div>
	<div id="collapseOne" class="panel-collapse collapse in">
	<div class="panel-body">

		<!-- ここから閉じる -->
		<table class="table table-bordered">
			<form action="" method="post" name="form1" id="">
			<thead>
			</thead>
			<tbody class="col-xs-8">
			<tr>
				<td class="info text-right col-xs-2">Company Code</td>
				<td class="col-xs-4">
					<div class="company_code">
						<div class="col-xs-12">
							<select name="selCompanyCode" onChange="changeCompanyCode(this)">
							  <option value="0" selected>(Company Code)
							  <option value="1">Company Code1
							  <option value="2">Company Code2
							  <option value="3">Company Code3
							  <option value="4">Company Code4
							  <option value="5">Company Code5
							  <option value="6">Company Code6
							</select>
						</div>
					</div>
				</td>
				<td class="info text-right col-xs-2">Profile Center</td>
				<td class="col-xs-4">
					<div class="company_code">
						<div class="col-xs-12">
							<select name='setProfileCenter'>
								<option value="0" selected>(Profile Center)
							</select>
						</div>
					</div>
				</td>
			</tr>


			<tr>
				<td class="info text-right">Engagement Code/Name</td>
				<td>
					<div class="col-xs-12">
						<input name='setEngagementCode' type="text" class="form-control">
					</div>
				</td>
				<td class="info text-right">Entity Code/Name</td>
				<td>
					<div class="company_code">
						<div class="col-xs-12">
							<input type="text" class="form-control">
						</div>
					</div>
				</td>
			</tr>
			<tr>
				<td class="info text-right">Engagement Start Date</td>
				<td>
					<div class="company_code">
						<div class="col-xs-5">
							<input type="text" class="form-control">
						</div>
					</div>
					<div class="col-xs-2">～</div>
					<div class="company_code">
						<div class="col-xs-5">
							<input type="text" class="form-control">
						</div>
					</div>
				</td>
				<td class="info text-right">EN</td>
				<td>
					<div class="company_code">
						<div class="col-xs-12">
							<input type="text" class="form-control">
						</div>
					</div>
				</td>
			</tr>

			<tr>
				<td class="info text-right">Engagement End Date</td>
				<td>
					<div class="company_code">
						<div class="col-xs-5">
							<input type="text" class="form-control">
						</div>
					</div>
					<div class="col-xs-2">～</div>
					<div class="company_code">
						<div class="col-xs-5">
							<input type="text" class="form-control">
						</div>
					</div>
				</td>
				<td class="info text-right">EP</td>
				<td>
					<div class="company_code">
						<div class="col-xs-12">
							<input type="text" class="form-control">
						</div>
					</div>
				</td>
			</tr>

			<tr>
				<td rowspan=2 class="info text-right">Fiscal End Date</td>
				<td rowspan=2>
					<div class="company_code">
						<div class="col-xs-5">
							<input type="text" class="form-control">
						</div>
					</div>
					<div class="col-xs-2">～</div>
					<div class="company_code">
						<div class="col-xs-5">
							<input type="text" class="form-control">
						</div>
					</div>
				</td>
				<td class="info text-right">Status</td>
				<td>
					<div class="col-xs-12">
					<input type="checkbox" name="Draft"  value="1" id="i1"><label for="i1">Draft</label>
					<input type="checkbox" name="Open"   value="1" id="i2"><label for="i2">Open</label>
					<input type="checkbox" name="Frozen" value="1" id="i3"><label for="i3">Frozen</label>
					<input type="checkbox" name="Close"  value="1" id="i4"><label for="i4">Close</label>
					</div>
				</td>
			</tr>

			<tr>
				<td class="info text-right">other</td>
				<td>
					<div class="col-xs-12">
						<input type="checkbox" name="amount_only" value="1" id="i5">
						<label for="i5">Actual Revenue Exceeded Contract Amount Only</label>
					</div>
				</td>
			</tr>
			</form>
			</tbody>
		</table>


		<!-- button -->
		<div class="col-xs-12">
			<button type="submit" class="btn btn-primary">Search</button>
			<button type="submit" class="btn btn-primary">Export</button>
			<button type="submit" class="btn btn-primary" onClick="clearButton()">Clear</button>
		</div>

		<!-- ここまで閉じる -->
	  </div>
	</div>
	</div>
	</div>

	<table>
		<tr>
			<td width=120><b>Total <%= @total_count %> results</b></td>
			<td><%= paginate(@engagements) %></td>
		</tr>
	</table>
	<table border="1">
	  <thead>
	    <tr>
	      <th>Engagement number</th>
	      <th>Engagement descr</th>
	      <th>Engagement legacy number</th>
	      <th>Em sap personnel number</th>
	      <th>Em legacy emplid</th>
	      <th>Ep sap personnel number</th>
	      <th>Ep legacy emplid</th>
	      <th>Erp realization rate</th>
	      <th>Entity number</th>
	      <th>Profit center</th>
	      <th>Local service type</th>
	      <th>Local service type descr</th>
	      <th>Company code</th>
	      <th>Engagement status</th>
	      <th>Engagement type</th>
	      <th>Profit center descr</th>
	      <th>Assistant name</th>
	      <th>Assistant sap personnel number</th>
	      <th>Assistant legacy emplid</th>
	      <th>Em name</th>
	      <th>Ep name</th>
	      <th>Engagement type descr</th>
	      <th>Entity name</th>
	      <th>Lead engagement number</th>
	      <th>San expirty date</th>
	      <th>Confidential engagment</th>
	      <th>San start date</th>
	      <th>Contract amount</th>
	      <th>Fiscal end date</th>
	      <th>Contract type</th>
	      <th>Deleted at</th>
	      <th>Created at</th>
	      <th>Updated at</th>
	      <th colspan="3"></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @engagements.each do |engagement| %>
	      <tr>
	        <td>￥<%= number_with_delimiter(engagement.engagement_number) %></td>
	        <td>
	        	<% if engagement.engagement_descr.to_s != "" %>
	        	<%= link_to engagement.engagement_descr, ect_engagement_class_plan_values_path(engagement.engagement_number) %>
	        	<% else %>
	        	<%= link_to "LINK", ect_engagement_class_plan_values_path(engagement.engagement_number) %>
	        	<% end %>
	        </td>
	        <td><%= engagement.engagement_legacy_number %></td>
	        <td><%= engagement.em_sap_personnel_number %></td>
	        <td><%= engagement.em_legacy_emplid %></td>
	        <td><%= engagement.ep_sap_personnel_number %></td>
	        <td><%= engagement.ep_legacy_emplid %></td>
	        <td><%= engagement.erp_realization_rate %></td>
	        <td><%= engagement.entity_number %></td>
	        <td><%= engagement.profit_center %></td>
	        <td><%= engagement.local_service_type %></td>
	        <td><%= engagement.local_service_type_descr %></td>
	        <td><%= engagement.company_code %></td>
	        <td><%= engagement.engagement_status %></td>
	        <td><%= engagement.engagement_type %></td>
	        <td><%= engagement.profit_center_descr %></td>
	        <td><%= engagement.assistant_name %></td>
	        <td><%= engagement.assistant_sap_personnel_number %></td>
	        <td><%= engagement.assistant_legacy_emplid %></td>
	        <td><%= engagement.em_name %></td>
	        <td><%= engagement.ep_name %></td>
	        <td><%= engagement.engagement_type_descr %></td>
	        <td><%= engagement.entity_name %></td>
	        <td><%= engagement.lead_engagement_number %></td>
	        <td><%= engagement.san_expirty_date %></td>
	        <td><%= engagement.confidential_engagment %></td>
	        <td><%= engagement.san_start_date %></td>
	        <td><%= engagement.contract_amount %></td>
	        <td><%= engagement.fiscal_end_date %></td>
	        <td><%= engagement.contract_type %></td>
	        <td><%= engagement.deleted_at.strftime("%Y-%m-%d") %></td>
	        <td><%= engagement.created_at.strftime("%Y-%m-%d") %></td>
	        <td><%= engagement.updated_at.strftime("%Y-%m-%d") %></td>
	        <td><%= link_to 'Show', ect_engagement_path(engagement) %></td>
	        <td><%= link_to 'Edit', edit_ect_engagement_path(engagement) %></td>
	        <td><%= link_to 'Destroy', ect_engagement_path(engagement), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>

<br>

※デバッグ追加用
<%= link_to 'New Engagement', new_ect_engagement_path %>

ibs_local_system_bk/app/views/ect/engagements/new.html.erb
<h1>New engagement</h1>

<%= render 'form' %>

<%= link_to 'Back', ect_engagements_path %>

ibs_local_system_bk/app/views/ect/plan_versions/index.html.erb
<h2>計画バージョン一覧表示</h2>

<!-- メニューやら何やら -->


	<table class="table table-bordered">
		<thead>
		</thead>
		<tbody>
		<tr>
			<td class="info text-right">Engagement</td>
			<td>コード＆名前</td>

			<td class="info text-right">Start Date/End Date</td>
			<td>日付 ～ 日付</td>

		</tr>
		</tbody>
	</table>

	<!-- button -->
	<%= button_to('Back', ect_engagement_class_plan_values_path(@engagement_id), :method => :get, :class => "btn btn-primary")  %>

	<br>

	<p>Total XX results</p>

	<table class="table table-bordered">

		<thead>
			<tr class="info text-right">
				<th>Version</th>
				<th>Last Update Date</th>
				<th>Last Update User</th>
				<th>ERP</th>
			</tr>
		</thead>

		<tbody>
			<tr>
				<td>
					20
	        		<%= link_to 'リンク', ect_engagement_plan_version_class_plan_values_path(@engagement_id, 20) %>
				</td>

				<td>2014-10-20 23:59:59</td>
				<td>test test</td>
				<td>50.00%</td>
			</tr>
		</tbody>

	</table>